### ISSUE TITLE
Plugin not working on KiCad 7

### ISSUE THREAD

**Issue by ShaojieHe** [mitxela/kicad-round-tracks#22] opened 2023-02-14 11:11 UTC
I download this plugin from KiCad PCM, upon use and showed this error when using this plugin.

![image](https://user-images.githubusercontent.com/49934147/218719735-70e4a681-8df4-4bfa-a1af-3c3aff245610.png)

**Comment by mitxela** [comment] 2023-02-14 17:12
I'm surprised the PCM even lets you download it as it's tagged only for KiCad 6, but yes there's some API changes that mean the plugin will need updating. I'm a bit too busy to do it right now but I'll get round to it eventually. Or if anyone else feels up for doing it feel free to submit a pull request.

**Comment by ShaojieHe** [comment] 2023-02-14 17:40
thanks for reply, Sorry I'm bad at python coding so I will leave it to others :)

**Comment by mitxela** [comment] 2023-02-15 12:11
Might as well leave this open so others can see it

**Comment by alinelena** [comment] 2023-02-22 19:59
I have tried today to see if I can update but somehow seems to be more complicated that expected... 

naively using self.board.GetAllNetClasses() results in 

![image](https://user-images.githubusercontent.com/3306823/220745108-c730041a-323a-42ee-a99a-abe14d5a98f9.png)

**Comment by mitxela** [comment] 2023-02-23 08:31
The netclass stuff was rewritten and the api is now a bit broken. I have submitted a pull request here: https://gitlab.com/kicad/code/kicad/-/merge_requests/1533
Once that (or something similar) gets merged, the plugin will work again, following the changes I pushed yesterday.

**Comment by benrogmans** [comment] 2023-02-23 21:09
Thanks for submitting that PR! I hope it gets merged soon :-)

**Comment by alinelena** [comment] 2023-02-25 10:16
I can confirm.. kicad patched with the 1533 and git plugin works.

**Comment by mitxela** [comment] 2023-02-25 13:48
It's merged, it should also get cherry-picked for 7.0.1. I will publish a new release when that comes out.

**Comment by mitxela** [comment] 2023-02-26 15:09
The patch is part of the nightly builds, so the plugin should work with those. I just added some very basic progress bar stuff, it would be helpful if someone can test it out on Mac as I only have Linux and Windows here.

**Comment by FrightRisk** [comment] 2023-02-27 21:33
It doesn't work for me. Windows 11, KiCAD 7 official release. I tried the install from the plugin manager, and of course it didn't work. But I wanted to get the folder name of where it wanted it. Then I unzipped master, copied it over everything in that folder (C:\Users\Fred\Documents\Kicad\7.0\3rdparty\plugins\com_github_mitxela_kicad-round-tracks), deleted the cache folder and tried again. I loads the first screen, I check the box to make a new file, and tell it to run. Another box pops up saying "processing", but nothing happens. I can't close the window because "close" is grayed out. It is stuck at "processing". I have to load the task manager to terminate KiCAD to be able to get out of it.
Then I saw that I needed the nightly build of KiCAD, so got this: [kicad-nightly-r31999.79f13ea9c7-x86_64-lite.exe] from today. I just installed over top of the one in the 7.0 folder instead of having yet an other 7.99 folder. It acted like a new install asking what settings I wanted, but everything is there. The about version says 7.99. I get the same exact error:

![image](https://user-images.githubusercontent.com/37218136/221690496-d3817fd5-6805-4ae2-b78d-d7072307afb1.png)

**Comment by alinelena** [comment] 2023-02-27 21:41
tested in linux and works... are you sure you put the new files from git in the right place?

I used the release script to bundle them in.

**Comment by FrightRisk** [comment] 2023-02-27 21:54
Working! You were right. I went to uninstall and realized that even though I said to copy things to the 7.0 folder, I could see 7.99. So I looked in preferences to see path locations and it still changed 2 of the paths (3rdparty being one of them) to 7.99. I think that is a bug in Kicad. I changed the paths to point to 7.0 and it worked. Thank you. I LOVE this plugin ;)

**Comment by endlessempathy** [comment] 2023-03-04 22:06
Somehow plugin doesn't work on latest 7.99 nightly build. I mean it works but does nothing. I also tried creating new project. It just shows progress bar, then shows popup saying that work is done but tracks are still "unrounded".
![Screenshot 2023-03-05 010501](https://user-images.githubusercontent.com/72225567/222930707-185c3c6f-44d3-4c74-be32-507c84277277.png)

**Comment by mitxela** [comment] 2023-03-05 13:54
It seems to still be working for me. I tried it on 7.99.0-342-gd714ff8549 with the latest version of round-tracks (c0a4fb8).

Can you try it on a very simple project? Also try running it with the scripting console open to see if there are any python errors. Otherwise maybe share a project where it's not working.

**Comment by endlessempathy** [comment] 2023-03-05 14:59
> 

Probably I'm just dumb and missing something, but I tried creating new project with just one trace and it still doing nothing.
I tried installing plugin (v1.2) from KiCad Plugin manager then changing files inside the folder to latest files from github and deleting __pycache__ folder, tried uninstalling that plugin and just unzipping current github repo (https://github.com/mitxela/kicad-round-tracks/commit/c0a4fb819697a50a7257ffe14afa4d7378cd3b88) into KiCad\7.99\3rdparty\plugins\kicad-round-tracks-master again. Getting no errors don't know what to do next. Should I delete 7.99 folder completely and try to reinstall KiCad?
![image](https://user-images.githubusercontent.com/72225567/222967385-cbf2ed57-7363-43de-9407-6e57ed42bc77.png)

**Comment by endlessempathy** [comment] 2023-03-05 15:15
> Should I delete 7.99 folder completely and try to reinstall KiCad?

Of course it worked 🙄 I fee so dumb now...
Anyway, thank you for your answer! Maybe if someone will encounter same problem they can see my msg.

**Comment by FrightRisk** [comment] 2023-03-06 13:20
I installed my KiCAD in the same 7.0 folder so I don't keep having to have a different folder (like 7.99) every time I install. But KiCAD leaves 2 of the folders pointing to the old folder name. No matter where you install it, you just have to make sure it is looking in the right place for the plugins

**Comment by mitxela** [comment] 2023-03-11 23:48
KiCad 7.0.1 is now released, you can download round tracks 1.4 from PCM.

**Closed by mitxela** 2023-03-11 23:48 UTC
